/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExpensesIndexImport } from './routes/expenses/index'
import { Route as ExpensesExpenseidImport } from './routes/expenses/$expenseid'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesIndexRoute = ExpensesIndexImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesExpenseidRoute = ExpensesExpenseidImport.update({
  id: '/expenses/$expenseid',
  path: '/expenses/$expenseid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/expenses/$expenseid': {
      id: '/expenses/$expenseid'
      path: '/expenses/$expenseid'
      fullPath: '/expenses/$expenseid'
      preLoaderRoute: typeof ExpensesExpenseidImport
      parentRoute: typeof rootRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/expenses/$expenseid': typeof ExpensesExpenseidRoute
  '/expenses': typeof ExpensesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/expenses/$expenseid': typeof ExpensesExpenseidRoute
  '/expenses': typeof ExpensesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/expenses/$expenseid': typeof ExpensesExpenseidRoute
  '/expenses/': typeof ExpensesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/expenses/$expenseid' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/expenses/$expenseid' | '/expenses'
  id: '__root__' | '/' | '/about' | '/expenses/$expenseid' | '/expenses/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ExpensesExpenseidRoute: typeof ExpensesExpenseidRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  ExpensesExpenseidRoute: ExpensesExpenseidRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/expenses/$expenseid",
        "/expenses/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/expenses/$expenseid": {
      "filePath": "expenses/$expenseid.tsx"
    },
    "/expenses/": {
      "filePath": "expenses/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
